"""Initial migration

Revision ID: 48262db30748
Revises: 
Create Date: 2025-04-20 02:43:47.212017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48262db30748'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_sum', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('rating_count')
        batch_op.drop_column('rating_sum')

    # ### end Alembic commands ###
